language: node_js
node_js:
  - '4'
  - '6'
  - '7'
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp yarn
  - yarn
script:
  - gulp build
after_success:
  - npm install -g semantic-release@^4.3.3
deploy:
  skip_cleanup: true
  provider: script
  script: semantic-release pre && npm publish && semantic-release post || true
  on:
    branch: master
    node: 7

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
